/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informe_final_win;

/**
 *
 * @author HP
 */
public class Proyecto_win extends javax.swing.JFrame {

    /**
     * Creates new form Proyecto_win
     */
    public Proyecto_win() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtDepartamento = new javax.swing.JTextField();
        jtxtNombre1 = new javax.swing.JTextField();
        jtxtApellidos = new javax.swing.JTextField();
        jtxtDNI = new javax.swing.JTextField();
        jtxtDireccion = new javax.swing.JTextField();
        jcbxPlan = new javax.swing.JComboBox<>();
        lbtnProcesar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jcbxPlan1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtDepartamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Distrito"));
        jtxtDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDepartamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 210, 80));

        jtxtNombre1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres"));
        jtxtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombre1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 160, 70));

        jtxtApellidos.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos"));
        jtxtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtApellidosActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 160, 70));

        jtxtDNI.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));
        jtxtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDNIActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 150, 70));

        jtxtDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Direccion"));
        getContentPane().add(jtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 270, 80));

        jcbxPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE MÉTODO DE PAGO--", "Visa", "MasterCard" }));
        getContentPane().add(jcbxPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 250, 70));

        lbtnProcesar.setText("PROCESAR DATOS");
        getContentPane().add(lbtnProcesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 170, 70));

        jButton2.setText("SALIR");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 90, 120, 70));

        jButton3.setText("CONFIRMAR PAGO");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 260, 70));

        jcbxPlan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE PLAN--", "100MB", "200MB", "600MB", "600MB PLUS", "1000MB" }));
        getContentPane().add(jcbxPlan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 200, 70));

        jTextField1.setText("Acá van los precios xd");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 330));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("RESUMEN DE DATOS"));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 870, 180));

        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("MONTO TOTAL A PAGAR"));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 260, 90));

        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder("MONTO POR INSTALACIÓN"));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 260, 90));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "DNI", "Distrito", "Direccion", "Monto de Instalación", "Monto Total"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 870, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDepartamentoActionPerformed

    private void jtxtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombre1ActionPerformed

    private void jtxtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtApellidosActionPerformed

    private void jtxtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDNIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto_win().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox<String> jcbxPlan;
    private javax.swing.JComboBox<String> jcbxPlan1;
    private javax.swing.JTextField jtxtApellidos;
    private javax.swing.JTextField jtxtDNI;
    private javax.swing.JTextField jtxtDepartamento;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtNombre1;
    private javax.swing.JButton lbtnProcesar;
    // End of variables declaration//GEN-END:variables
}
